
# Data Description
To approach this task, data from multiple sources was used.
The primary dataset used in this analysis is the Chicago Taxi Trips dataset [@chicago_taxi_2024], 
which is publicly available via the Chicago Data Portal and contains taxi trips from 2024 onwards. The Taxi Trip Dataset contains one trip per row, 
with timestamps rounded to the nearest 15 minutes. Since the full dataset starting from 2024 contains over 16 million rows, the dataset was
limited to only include trips from 2025, resulting in a raw dataset of roughly 6.8 million rows. Important attributes include trip and taxi identifiers, the timestamp of the trip, 
centroid coordinates of the community area or census tract where the trip took place and multiple attributes about the trips properties like price or length (@fig-raw-trip-columns).

Furthermore, hourly Chicago weather data was obtained from the Open-Meteo API [@openmeteo2026] for the period of January 2024 to January 2026.
The initial dataset includes roughly 17500 entries and key variables of the dataset include temperature, precipitation and sunshine duration (@fig-weather-columns). 


Points-of-Interest data for Chicago was gathered from OpenStreetMap via the Overpass API [@overpassapi2026], covering nine categories: airports, train stations, stadiums, restaurants, 
bars and clubs, hotels, hospitals, universities, and tourist attractions. These raw POI locations are subsequently aggregated into distance and density features for multiple spatial resolutions
during data preparation.

In order to be able to analyse the data on census tract and community area level, additional geometry data containing the shapes of these areas was obtained. These datasets contain the geometry
for Chicago's 77 community areas and 878 census tracts.


